<div class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <b class="caret"></b>
    </a>
    <ul class="dropdown-menu pull-right">
        <li><a href="#"><i class="icon-share"></i> <?php echo $this->tr("VIEW"); ?></a></li>
        <li><a href="#" rel="modal" data-resource="_admin_user_edit" data-id="<?php echo $this->user->getId() ?>"><i class="icon-edit"></i> <?php echo $this->tr("EDIT"); ?></a></li>
        <li><a href="#"><i class="icon-remove"></i> <?php echo $this->tr("REMOVE"); ?></a></li>
    </ul>
</div>
