<div class="control-group">
    <label class="control-label" for="category_parent"><?php echo $this->tr("CATEGORY_PARENT"); ?>:</label>
    <div class="controls">
        <select id="category_parent" name="category[parent]" class="span12">
            <option value="0">No parent</option>
            <?php echo $this->partial("categoriesList.phtml", "Classified", array("active"=>@$this->category['parent'])); ?>
        </select>
    </div>
</div>
<div class="control-group">
    <label class="control-label" for="category_name"><?php echo $this->tr("CATEGORY_NAME"); ?>:</label>
    <div class="controls">
        <input type="text" id="category_name" name="category[name]" value="<?php echo @$this->category['name']; ?>" class="span12"/>
    </div>
</div>
<div class="control-group">
    <div class="controls">
        <label class="checkbox">
            <input<?=$this->checkedIf(@$this->category['postable'])?> type="checkbox" id="category_postable" name="category[postable]"/>
            <?php echo $this->tr("CATEGORY_POSTABLE"); ?>
        </label>
    </div>
</div>