<div class="modal fade" id="_admin_question_new" style="display: none;">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">×</button>
        <h3><?php echo $this->translate('NEW_QUESTION'); ?></h3>
    </div>
    <div class="modal-body">
        <div class="row-fluid">
        <div id="_admin_question_new_messages"></div>
        <form action="<?php echo $this->url(array("controller"=>"question", "action"=>"create", "format"=>"json"), "classified", true); ?>" id="_admin_question_new_form" method="post">
            <div class="control-group">
                <label class="control-label" for="question_type"><?php echo $this->tr("QUESTION_TYPE"); ?>:</label>
                <div class="controls">
                    <select id="question_type" name="question[type]" class="span12">
                        <option<?php echo $this->selectedIf(@$this->question['name']=='text')?> value="text">Text field</option>
                        <option<?php echo $this->selectedIf(@$this->question['name']=='textarea')?> value="textarea">Long text field</option>
                        <option<?php echo $this->selectedIf(@$this->question['name']=='select')?> value="select">Select field</option>
                        <option<?php echo $this->selectedIf(@$this->question['name']=='ranged')?> value="ranged">Ranged field</option>
                        <option<?php echo $this->selectedIf(@$this->question['name']=='checkbox')?> value="checkbox">Checkbox</option>
                    </select>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="question_name"><?php echo $this->tr("QUESTION_NAME"); ?>:</label>
                <div class="controls">
                    <input type="text" id="question_name" name="question[name]" value="<?php echo @$this->question['name']; ?>" class="span12"/>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="question_predefined"><?php echo $this->tr("QUESTION_PREDEFINED"); ?>:</label>
                <div class="controls">
                    <textarea id="question_predefined" name="question[predefined]" class="span12" rows="3"><?php echo @$this->question['predefined']; ?></textarea>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="question_description"><?php echo $this->tr("QUESTION_DESCRIPTION"); ?>:</label>
                <div class="controls">
                    <textarea id="question_description" name="question[description]" class="span12" rows="3"><?php echo @$this->question['description']; ?></textarea>
                </div>
            </div>
        </form>
        </div>
    </div>
    <div class="modal-footer">
        <a href="#" class="btn" data-dismiss="modal"><?php echo $this->tr("BACK_BTN"); ?></a>
        <a class="btn btn-primary" id="_admin_question_new_submit"><?php echo $this->tr("SUBMIT"); ?></a>
    </div>
</div>

<script type="text/javascript">//<![CDATA[
$('#question_type').trigger('change');
//]]></script>