<div class="navbar">
    <div class="navbar-inner">
        <a class="brand" href="<?php echo $this->baseUrl()?>/"><?php echo $this->tr("SITE_TITLE"); ?></a>
        <ul class="nav">
            <li<?php echo $this->activeIf($this->active_tab=="home");?>><a href="<?php echo $this->url(array(), "admin", true); ?>">Home</a></li>
            <li<?php echo $this->activeIf($this->active_tab=="users");?>><a href="<?php echo $this->url(array("controller"=>"user"), "admin", true); ?>">Users</a></li>
        </ul>
    </div>
</div>
