<div class="row-fluid">
<form action="<?php echo $this->url(array("id"=>$this->user['id'], "action"=>"edit"), "profile", true); ?>" method="post" class="">
    <input type="hidden" id="user_id" name="user[id]" value="<?php echo @$this->user['id']; ?>" />
    <div class="control-group">
        <label class="control-label" for="user_username"><?php echo $this->tr("USERNAME"); ?>:</label>
        <div class="controls">
            <input type="text" id="user_username" name="user[username]" value="<?php echo @$this->user['username']; ?>" class="span12" />
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="user_email"><?php echo $this->tr("EMAIL"); ?>:</label>
        <div class="controls">
            <input type="text" id="user_email" name="user[email]" value="<?php echo @$this->user['email']; ?>" class="span12"/>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="user_phone"><?php echo $this->tr("PHONE"); ?>:</label>
        <div class="controls">
            <input type="text" id="user_phone" name="user[phone]" value="<?php echo @$this->user['phone']; ?>" class="span12"/>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="user_url"><?php echo $this->tr("URL"); ?>:</label>
        <div class="controls">
            <input type="text" id="user_url" name="user[url]" value="<?php echo @$this->user['url']; ?>" class="span12"/>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="user_description"><?php echo $this->tr("DESCRIPTION"); ?>:</label>
        <div class="controls">
            <textarea rows="5" id="user_description" name="user[description]" class="span12"><?php echo @$this->user['description']; ?></textarea>
        </div>
    </div>

    <div class="form-actions">
        <button type="submit" class="btn btn-primary"><?php echo $this->tr("SAVE_BTN"); ?></button>
    </div>
</form>
</div>
