<div class="control-group">
    <label class="control-label" for="advert_answers_<?=$this->q->getId()?>"><?php echo $this->tr($this->q->getName()); ?>:</label>
    <div class="controls">
        <select class="span12" id="advert_answers_<?=$this->q->getId()?>" name="advert[answers][<?=$this->q->getId()?>]">
<?php foreach (preg_split("/\n/",$this->q->getPredefined()) as $pre): ?>
            <option<?=$this->selectedIf($this->a==$pre)?>><?php echo $pre?></option>
<?php endforeach; ?>
        </select>
    </div>
</div>