<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title><?php echo $this->tr("SITE_TITLE"); ?></title>

        <link href="<?php echo $this->baseUrl()?>/css/admin.min.css" media="screen" rel="stylesheet" type="text/css" >
        <link href="<?php echo $this->baseUrl()?>/css/jquery.lightbox.css" media="screen" rel="stylesheet" type="text/css" >
        <?php echo $this->headLink(); ?>

    </head>
    <body>
        <div class="container wrapper">
            <?php echo $this->layout()->navbar; ?>

            <div class="row-fluid content">
            <?php echo $this->layout()->content; ?>

            </div>
        </div>

        <script type="text/javascript" src="<?php echo $this->baseUrl()?>/js/jquery.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl()?>/js/jquery.lightbox.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl()?>/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl()?>/js/core.js"></script>
        <?php echo $this->headScript(); ?>

    </body>
</html>