<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle(); ?>

        <?php echo $this->headLink(); ?>

    </head>
    <body>
        <div class="container wrapper">
            <?php echo $this->layout()->navbar; ?>

            <div class="row-fluid content">
            <?php echo $this->layout()->content; ?>

            </div>
        </div>

        <?php echo $this->headScript(); ?>

    </body>
    <!-- <?php echo "rendered in " . round(microtime(true) - Zend_Registry::get("start_time"), 3) . "s";?> -->
</html>