<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle(); ?>

        <?php echo $this->headLink(); ?>

    </head>
    <body>
        <div class="container wrapper">
            <div class="row-fluid header">
                <a href="<?php echo $this->baseUrl()?>/" class="pull-left">
                    <span style="line-height: 65px;">Logo</span>
                </a>

                <ul class="nav nav-pills pull-right">
                    <li><a href="<?php echo $this->url(array("action"=>"new"), "adverts", true); ?>"><?php echo $this->tr("POST_AD"); ?></a></li>
<?php if (is_null($this->currentUser())) : ?>
                    <li><a href="<?php echo $this->url(array(), "signup", true); ?>"><?php echo $this->tr("SIGNUP"); ?></a></li>
<?php else : ?>
                    <li><a href="<?php echo $this->url(array("id"=>$this->currentUser()->getId(), "action"=>"edit"), "profile", true); ?>"><?php echo $this->currentUser()->getUsername(); ?></a></li>
                    <li><a href="<?php echo $this->url(array(), "logout", true); ?>"><?php echo $this->tr("LOGOUT"); ?></a></li>
<?php endif; ?>
                </ul>
            </div>
            <div class="row-fluid content">
            <?php echo $this->layout()->content; ?>

            </div>
            <div class="push"></div>
        </div>
        <div class="container">
            <div class="row-fluid footer">
                <ul>
                    <li><a href=""><?php echo $this->translate('Link'); ?></a></li>
                </ul>
            </div>
        </div>

        <?php echo $this->headScript(); ?>

    </body>
    <!-- <?php echo "rendered in " . round(microtime(true) - Zend_Registry::get("start_time"), 3) . "s";?> -->
</html>