<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="utf-8">
        <title><?php echo $this->tr("SITE_TITLE"); ?></title>

        <link href="<?php echo $this->baseUrl()?>/css/core.min.css" media="screen" rel="stylesheet" type="text/css" >
        <link href="<?php echo $this->baseUrl()?>/css/jquery.lightbox.css" media="screen" rel="stylesheet" type="text/css" >
        <?php echo $this->headLink(); ?>

    </head>
    <body>
        <div class="container wrapper">
            <div class="row-fluid header">
                <a href="<?php echo $this->baseUrl()?>/" class="pull-left">
                    <img src="" alt="Logo" class="logo" />
                </a>

                <ul class="nav nav-pills pull-right">
<?php if (is_null($this->currentUser())) : ?>
                    <li><a href="<?php echo $this->url(array(), "signup", true); ?>"><?php echo $this->tr("SIGNUP"); ?></a></li>
                    <li><a href="<?php echo $this->url(array(), "login", true); ?>"><?php echo $this->tr("LOGIN"); ?></a></li>
<?php else : ?>
                    <li><a href="<?php echo $this->url(array("id"=>$this->currentUser()->getId()), "profile", true); ?>"><?php echo $this->currentUser()->getUsername(); ?></a></li>
                    <li><a href="<?php echo $this->url(array(), "logout", true); ?>"><?php echo $this->tr("LOGOUT"); ?></a></li>
<?php endif; ?>
                </ul>
            </div>
            <div class="row-fluid content">
            <?php echo $this->layout()->content; ?>

            </div>
            <div class="push"></div>
        </div>
        <div class="container">
            <div class="row-fluid footer">
                <ul>
                    <li><a href=""><?php echo $this->translate('Link'); ?></a></li>
                </ul>
            </div>
        </div>

        <script type="text/javascript" src="<?php echo $this->baseUrl()?>/js/jquery.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl()?>/js/jquery.lightbox.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl()?>/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl()?>/js/core.min.js"></script>
        <?php echo $this->headScript(); ?>

    </body>
</html>