<div class="row-fluid">
  <div class="span3"></div>
  <div class="span6 form">
    <div class="form_head">
        <div class="bheadl"></div>
        <div class="bheadr"></div>
        <h2><?php echo $this->translate('Signup'); ?></h2>
    </div>
    <div class="form_content">
      <?php echo $this->messages(); ?>
      <?php echo $this->partial("registration/_form.phtml", "user", array("user"=>$this->user)); ?>
    </div>
  </div>
  <div class="span3"></div>
</div>
