<?php
    // set title
    $this->headTitle()->prepend("Admin");
    $this->headTitle()->prepend("Categories");

    $this->addChosen(); // add chosen to head
?>
<!-- header -->
<div class="page-header">
    <h3>
        <?php echo $this->tr("EDIT_CATEGORY"); ?>
        <small>"<?php echo $this->category['name'] ?>"</small>
    </h3>
    <ul class="nav nav-pills">
    <li><a href="<?php echo $this->url(array("controller"=>"category"), "admin", true); ?>">
        <i class="icon-arrow-left"></i> Back to categories list
    </a></li>
    </ul>
</div>
<!-- /header -->

<div class="row-fluid">
    <div class="span6">
    <?php echo $this->messages(); ?>
    <form action="<?php echo $this->url(array("controller"=>"category", "action"=>"update", "id"=>$this->category['id']), "classified", true); ?>" method="post">
        <?php echo $this->partial("category/_form.phtml", "Classified", array("category"=>$this->category)); ?>
    </form>
    </div>
    <div class="span6"></div>
</div>
