<!-- header -->
<div class="page-header">
    <h3><?php echo $this->tr("EDIT_CATEGORY"); ?></h3>
    <ul class="nav nav-pills">
    <li><a href="<?php echo $this->url(array("controller"=>"category"), "admin", true); ?>">
        <i class="icon-arrow-left"></i> Back to categories list
    </a></li>
    </ul>
</div>
<!-- /header -->

<div class="row-fluid">
<div class="span6" style="background: #eee;">
    left
</div>
<div class="span6">
    right
</div>
</div>