<div class="modal fade" id="_admin_category_new" style="display: none;">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">×</button>
        <h3><?php echo $this->translate('NEW_CATEGORY'); ?></h3>
    </div>
    <div class="modal-body">
        <div class="row-fluid">
        <div id="_admin_category_new_messages"></div>
        <form action="<?php echo $this->url(array("controller"=>"category", "action"=>"create", "format"=>"json"), "classified", true); ?>" id="_admin_category_new_form" method="post">
            <?php echo $this->partial("category/_form.phtml", "Classified", array("category"=>$this->category)); ?>
        </form>
        </div>
    </div>
    <div class="modal-footer">
        <a href="#" class="btn" data-dismiss="modal"><?php echo $this->tr("BACK_BTN"); ?></a>
        <a class="btn btn-primary" id="_admin_category_new_submit"><?php echo $this->tr("SUBMIT"); ?></a>
    </div>
</div>
